/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cis355a_wk3_lab;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Payden Boughton
 */
public class BurgerGUI extends javax.swing.JFrame {

    private double orderTotal;
    private static DecimalFormat d2 = new DecimalFormat("#,##0.00");
    /**
     * Creates new form BurgerGUI
     */
    public BurgerGUI() {
        initComponents();
        //after GUI built center it
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgBurgers = new javax.swing.ButtonGroup();
        singleRad = new javax.swing.JRadioButton();
        doubleRad = new javax.swing.JRadioButton();
        cheeseCheckbox = new javax.swing.JCheckBox();
        baconCheckbox = new javax.swing.JCheckBox();
        mealCheckbox = new javax.swing.JCheckBox();
        lblOrder = new javax.swing.JLabel();
        orderScrollPane = new javax.swing.JScrollPane();
        orderTextArea = new javax.swing.JTextArea();
        lblItemPrice = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblOrderTotal = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        totalTextField = new javax.swing.JTextField();
        itemPriceTextField = new javax.swing.JTextField();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuitem = new javax.swing.JMenuItem();
        orderMenu = new javax.swing.JMenu();
        addOrdermenuBtn = new javax.swing.JMenuItem();
        clearTextbtn = new javax.swing.JMenuItem();
        neworderBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burger Barn");

        btgBurgers.add(singleRad);
        singleRad.setText("Single Burger");
        singleRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleRadActionPerformed(evt);
            }
        });

        btgBurgers.add(doubleRad);
        doubleRad.setText("Double Burger");
        doubleRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleRadActionPerformed(evt);
            }
        });

        cheeseCheckbox.setText("Add cheese");
        cheeseCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseCheckboxActionPerformed(evt);
            }
        });

        baconCheckbox.setText("Add bacon");
        baconCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconCheckboxActionPerformed(evt);
            }
        });

        mealCheckbox.setText("Make it a meal");
        mealCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealCheckboxActionPerformed(evt);
            }
        });

        lblOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOrder.setText("YOUR ORDER");

        orderTextArea.setColumns(20);
        orderTextArea.setRows(5);
        orderScrollPane.setViewportView(orderTextArea);

        lblItemPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblItemPrice.setText("Item Price:");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuantity.setText("Quantity:");

        lblOrderTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOrderTotal.setText("Order Total:");

        quantityTextField.setText("1");
        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });

        totalTextField.setEditable(false);
        totalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextFieldActionPerformed(evt);
            }
        });

        itemPriceTextField.setText("0");
        itemPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPriceTextFieldActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        exitMenuitem.setText("Exit");
        exitMenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuitemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuitem);

        mainMenuBar.add(fileMenu);

        orderMenu.setText("Order");

        addOrdermenuBtn.setText("Add to Order");
        addOrdermenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrdermenuBtnActionPerformed(evt);
            }
        });
        orderMenu.add(addOrdermenuBtn);

        clearTextbtn.setText("Clear for next item");
        clearTextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextbtnActionPerformed(evt);
            }
        });
        orderMenu.add(clearTextbtn);

        neworderBtn.setText("New Order");
        neworderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neworderBtnActionPerformed(evt);
            }
        });
        orderMenu.add(neworderBtn);

        mainMenuBar.add(orderMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOrder)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mealCheckbox)
                            .addComponent(doubleRad)
                            .addComponent(cheeseCheckbox)
                            .addComponent(baconCheckbox)
                            .addComponent(singleRad))
                        .addGap(46, 46, 46)
                        .addComponent(orderScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderTotal)
                            .addComponent(lblItemPrice)
                            .addComponent(lblQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblOrder)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(singleRad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doubleRad)
                        .addGap(18, 18, 18)
                        .addComponent(cheeseCheckbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(baconCheckbox)
                        .addGap(18, 18, 18)
                        .addComponent(mealCheckbox))
                    .addComponent(orderScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderTotal))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextFieldActionPerformed

    private void exitMenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuitemActionPerformed
        // exit application
        System.exit(0);
    }//GEN-LAST:event_exitMenuitemActionPerformed

    private void singleRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleRadActionPerformed
        //single burger chosen
        //JOptionPane.showMessageDialog(this, "Single Burger");
        calcPrice();
    }//GEN-LAST:event_singleRadActionPerformed

    private void doubleRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleRadActionPerformed
        //double burger chosen
       // JOptionPane.showMessageDialog(this, "Double Burger");
       calcPrice();
    }//GEN-LAST:event_doubleRadActionPerformed

    private void itemPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPriceTextFieldActionPerformed

    private void cheeseCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseCheckboxActionPerformed
        // update cost
        //JOptionPane.showMessageDialog(this, "add Cheese");
        calcPrice();
    }//GEN-LAST:event_cheeseCheckboxActionPerformed

    private void baconCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconCheckboxActionPerformed
        // update cost
       // JOptionPane.showMessageDialog(this, "add Bacon");
       calcPrice();
    }//GEN-LAST:event_baconCheckboxActionPerformed

    private void mealCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealCheckboxActionPerformed
        // update cost
        //JOptionPane.showMessageDialog(this, "Make Meal");
        calcPrice();
    }//GEN-LAST:event_mealCheckboxActionPerformed

    private void addOrdermenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrdermenuBtnActionPerformed
        //increas total price
        double itemTotal = Double.parseDouble(itemPriceTextField.getText());
        orderTotal += itemTotal;
        
        totalTextField.setText(d2.format(orderTotal));
        //add to order details
        //2 double, cheese, meal at 9.25 each
        int quantity = Integer.parseInt(quantityTextField.getText());
        String type = "";
        if (singleRad.isSelected()) 
            type = "single";
        else 
            type = "double";
        
        String cheese = "", bacon = "", meal = "";
                if (cheeseCheckbox.isSelected())
                    cheese = ", cheese";
                if (baconCheckbox.isSelected())
                    bacon = ", bacon";
                if (mealCheckbox.isSelected())
                    meal = ", meal";
                
                orderTextArea.append(quantity + " " + type + cheese + bacon + meal + " at " + d2.format(itemTotal) + " each\n");
        
    }//GEN-LAST:event_addOrdermenuBtnActionPerformed

    private void clearTextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextbtnActionPerformed
        // clear for next item
        btgBurgers.clearSelection();
        cheeseCheckbox.setSelected(false);
        baconCheckbox.setSelected(false);
        mealCheckbox.setSelected(false);
        itemPriceTextField.setText("");
        quantityTextField.setText("");
        
        
    }//GEN-LAST:event_clearTextbtnActionPerformed

    private void neworderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neworderBtnActionPerformed
        // new order
        //JOptionPane.showMessageDialog(this, "new order");
        orderTotal = 0.0;
        totalTextField.setText("");
        btgBurgers.clearSelection();
        cheeseCheckbox.setSelected(false);
        baconCheckbox.setSelected(false);
        mealCheckbox.setSelected(false);
        itemPriceTextField.setText("");
        quantityTextField.setText("");
        orderTextArea.setText("");
    }//GEN-LAST:event_neworderBtnActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // quantity changed
        //JOptionPane.showMessageDialog(this, "ActionPerformed");
        calcPrice();
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addOrdermenuBtn;
    private javax.swing.JCheckBox baconCheckbox;
    private javax.swing.ButtonGroup btgBurgers;
    private javax.swing.JCheckBox cheeseCheckbox;
    private javax.swing.JMenuItem clearTextbtn;
    private javax.swing.JRadioButton doubleRad;
    private javax.swing.JMenuItem exitMenuitem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField itemPriceTextField;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JCheckBox mealCheckbox;
    private javax.swing.JMenuItem neworderBtn;
    private javax.swing.JMenu orderMenu;
    private javax.swing.JScrollPane orderScrollPane;
    private javax.swing.JTextArea orderTextArea;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JRadioButton singleRad;
    private javax.swing.JTextField totalTextField;
    // End of variables declaration//GEN-END:variables

    private void calcPrice() {
        double itemPrice = 0;
        
        //get price of burger (base)
        if (singleRad.isSelected())
        {
            itemPrice = 3.50;
        }
        else 
        {
            itemPrice = 4.75;
        }
        
        //check options add to item price
        if(cheeseCheckbox.isSelected())
            itemPrice = itemPrice += 0.50;
        if(baconCheckbox.isSelected())
            itemPrice = itemPrice += 1.25;
        if(mealCheckbox.isSelected())
            itemPrice = itemPrice += 4.00;
        
        //include the quantity for the item price
        int quantity= 1;
        if (quantityTextField.getText().equals(""))
            quantityTextField.setText("1");
         quantity = Integer.parseInt(quantityTextField.getText());
        itemPrice = itemPrice * quantity;

        
        //show the price no $ symbol
        
        itemPriceTextField.setText(d2.format(itemPrice));
    }
}
